theme: jekyll-theme-cayman
title: Welcome to the 1st IIBM Networking!
description: [Important dates](#important-dates); [Student presentations](#student-presentations) ; [Proposals](#proposals); [Schedule](#schedule)
github:
  is_project_page: false
